version: '3'

services:
  cornflow:
    image: baobabsoluciones/cornflow:latest
    restart: always
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=flaskr.app
      - FLASK_ENV=development
      - DATABASE_URL=postgres://postgres:postgresadmin@cornflow_db:5432/cornflow
      - SECRET_KEY=THISNEEDSTOBECHANGED
      - AIRFLOW_URL=http://changethistoairflowurl:8080
      - CORNFLOW_URL=http://cornflow:5000
    depends_on:
      - cornflow_db

  cornflow_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresadmin
      - POSTGRES_DB=cornflow
    volumes:
      - postgres_cf_data:/var/lib/postgresql/data/

volumes:
  postgres_cf_data:
