version: '3'

services:
  webserver:
    build:
      context: ./airflow_config
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./airflow_config/dags:/usr/local/airflow/dags
      - ./airflow_config/requirements.txt:/requirements.txt
    environment:
      - AIRFLOW_USER=admin
      - AIRFLOW_PWD=admin
      - CORNFLOW_SERVICE_USER=service_user@cornflow.com
      - CORNFLOW_SERVICE_PWD=Serviceuser_1234
      - AIRFLOW_DB_HOST=airflow_db
      - AIRFLOW_DB_PORT=5432
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
      - AIRFLOW_DB=airflow
      - AIRFLOW__CORE__FERNET_KEY=L5Z7WRVv5zaexK0OL3pS2stYUF-gx_UmfDBqWQ4br6Y=
      - EXECUTOR=Celery
    ports:
      - 8080:8080
    depends_on:
      - airflow_db
      - redis
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 5

  scheduler:
    build:
      context: ./airflow_config
      dockerfile: Dockerfile
    restart: always
    depends_on:
        - webserver
    volumes:
      - ./airflow_config/dags:/usr/local/airflow/dags
      - ./airflow_config/requirements.txt:/requirements.txt
    environment:
      - AIRFLOW_USER=admin
      - AIRFLOW_PWD=admin
      - CORNFLOW_SERVICE_USER=service_user@cornflow.com
      - CORNFLOW_SERVICE_PWD=Serviceuser_1234
      - AIRFLOW_DB_HOST=airflow_db
      - AIRFLOW_DB_PORT=5432
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
      - AIRFLOW_DB=airflow
      - AIRFLOW__CORE__FERNET_KEY=L5Z7WRVv5zaexK0OL3pS2stYUF-gx_UmfDBqWQ4br6Y=
      - EXECUTOR=Celery
    command: scheduler

  flower:
    build:
      context: ./airflow_config
      dockerfile: Dockerfile
    restart: always
    depends_on:
        - redis
    environment:
      - AIRFLOW_DB_HOST=airflow_db
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
      - EXECUTOR=Celery
    ports:
        - "5555:5555"
    command: flower

  airflow_db:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_af_data:/var/lib/postgresql/data/
  
  redis:
    image: redis:5.0.5

  worker:
    build:
      context: ./airflow_config
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./airflow_config/dags:/usr/local/airflow/dags
      - ./airflow_config/requirements.txt:/requirements.txt
    environment:
      - AIRFLOW_DB_HOST=airflow_db
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
      - AIRFLOW__CORE__FERNET_KEY=L5Z7WRVv5zaexK0OL3pS2stYUF-gx_UmfDBqWQ4br6Y=
      - EXECUTOR=Celery
    command: worker

volumes:
  postgres_af_data:
